eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: ${spring.cloud.client.ip-address}
      instanceId: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 8763
spring:
  application:
    name: eurekaclient
